### PR TITLE
Added more movable buttons

### PR DESCRIPTION
**Pull request by Silver-Snail**
Hey, sometime or other could you perchance separate the joystick from the main cockpit, or would that mess things up? Not as a separate file, just a separate object within the newcockpit.ac file.

### CODE REVIEW

**Comment by racerretrocoder** [comment]
Sure. What is your main 3d modeler you use?

**Comment by Silver-Snail** [comment]
I have access to Blender, Fusion 360, and Onshape. Another idea I had was to make another folder with all the models in a format that those of us that don't have AC3D can use, kind of like the c172 has. Just a thought.

**Comment by racerretrocoder** [comment]
I have AC3d. But due to my power supply in my computer. I am unable to power my rtx3060 So its a bit hard to Move a large amount of vertex's 

But i can try though

**Comment by racerretrocoder** [comment]
The moving buttons are Awesome!! I've always struggled to try and get them working my self.  Thank you!!!

**Comment by Silver-Snail** [comment]
> I have AC3d. But due to my power supply in my computer. I am unable to power my rtx3060 So its a bit hard to Move a large amount of vertex's
> 
> But i can try though

If you export is as like an OBJ or 3mf or something I could do it for you, if you wish.

**Comment by Silver-Snail** [comment]
> The moving buttons are Awesome!! I've always struggled to try and get them working my self. Thank you!!!

I did too for a while, but then I discovered you can both rotate and translate simultaneously, and that changed everything!

**Comment by Silver-Snail** [comment]
Also, I got the throttle stick to be dynamic, but the bottom of it is not a full circle so it looks a little weird when it rotates. If you want to change that too then I can push that change too.

**Comment by racerretrocoder** [comment]
Sure

**Comment by racerretrocoder** [comment]
Im going to add some labels for the switch's

**Comment by racerretrocoder** [comment]
And do somthing cool for the MFD ;)

**Comment by racerretrocoder** [comment]
Screenshot (1512)
lol

**Comment by racerretrocoder** [comment]
image
Fixed it. Thats better

**Comment by racerretrocoder** [comment]
image
Now i need edit some code to disable the h key from turning on the hud. 
or i can make h just flick the switch

**Comment by racerretrocoder** [comment]
image
Ok the HUD panel is done. All that's left is to make the alpha/bright knobs a line on top so we now what its set to

**Comment by Silver-Snail** [comment]
AC3D may run smoother if you close everything else out... 🤣🤣 Also, how much should the throttle stick and joystick move?

**Comment by Silver-Snail** [comment]
> image Ok the HUD panel is done. All that's left is to make the alpha/bright knobs a line on top so we now what its set to

Sweet!

**Comment by racerretrocoder** [comment]
The F-16's Joystick moves very slightly. So the pilot can use under g forces. im guessing its the same way for the f22

**Comment by racerretrocoder** [comment]
image
@Silver-Snail

**Comment by racerretrocoder** [comment]
https://discord.gg/373jb5Fc oh and i also made a dev server

**Comment by Silver-Snail** [comment]
image
Here's what I see.

**Comment by Silver-Snail** [comment]
> https://discord.gg/373jb5Fc oh and i also made a dev server

Unfortunately I don't have access to discord.

**Comment by racerretrocoder** [comment]
Hmmmm. Lol  Try going to Debug --> Reload aircraft Model

**Comment by racerretrocoder** [comment]
ok

**Comment by racerretrocoder** [comment]
image
I made a sphere on the bottom of the stick

**Comment by racerretrocoder** [comment]
You dont need to make an animation for the sphere to move. Just the stick. UNLESS if the og sphere clips through it

**Comment by racerretrocoder** [comment]
Let me repos this then i will do throttle next

**Comment by racerretrocoder** [comment]
Ok stick replaced 
image

**Comment by racerretrocoder** [comment]
image
The stick is now also its own object. Its name is: Stick

**Comment by racerretrocoder** [comment]
image
Done with throt. The Object name for it is: throt

**Comment by racerretrocoder** [comment]
Ok i shall now reposition the new throttle

**Comment by racerretrocoder** [comment]
Oh and snail. Next time we fly together can we fly really close to make a new splash screen?

**Comment by Silver-Snail** [comment]
> Oh and snail. Next time we fly together can we fly really close to make a new splash screen?

Sure!

**Comment by Silver-Snail** [comment]
It's looking amazing, but I am running into a problem. I don't know the exact point to rotate around, and the loc in the ac file isn't accurate. Is it too much to ask if you could find them?

**Comment by racerretrocoder** [comment]
Should i like create like a Really small cube under the center of the joystick as the point.
i dont know how to get the point data. is it encoded in the .ac file? when opened in a text editor
i wonder if the data for stick is pointing at the middle of it

**Comment by racerretrocoder** [comment]
im making an ejection lever too

**Comment by Silver-Snail** [comment]
> Should i like create like a Really small cube under the center of the joystick as the point. i dont know how to get the point data. is it encoded in the .ac file? when opened in a text editor i wonder if the data for stick is pointing at the middle of it

No need to because I got it.

**Pull request merged**
