### PR TITLE
Update the engine autostarted branch

### PR DESCRIPTION
**Pull request by racerretrocoder**

### CODE REVIEW

**Comment by MonotoneDevelopment** [comment]
Phoenix, what the hell have you been doing? stealing more code?

**Comment by racerretrocoder** [comment]
No :)

**Comment by racerretrocoder** [comment]
FDM was made by a program called aeromatic (Google it   JSBSIM aeromatic) Then I edited it to add functions for the vectors. 
I made the the cockpit autopilot integration system! 100% with references from the FG wiki

**Comment by racerretrocoder** [comment]
More cockpit funtions. i neeeeddd moreeee.. there sooo much fun! to make and use

**Pull request merged**
